name: "Test issue comments"
on:
  issue_comment:
    types: [created]

jobs:
  execute:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Echo PR number
        run: echo "PR number is ${{ github.event.issue.number }}"
      - name: Call reusable workflow
        uses: ./.github/workflows/reusable.yaml
        with:
          pr_number: ${{ github.event.issue.number }}
